(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "cask")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "eproject")
(depends-on "f")
(depends-on "floobits")
(depends-on "gist")
(depends-on "pallet")
(depends-on "s")